from django.urls import path

from .views import (
    CatalogFolderView,
    CatalogTrashView,
    CreateFolderView,
    RenameCatalogFolderView,
    MoveCatalogFolderView,
    DeleteCatalogFolderView,
    UploadCatalogDocumentView,
    DownloadCatalogDocumentView,
    RenameCatalogDocumentView,
    MoveCatalogDocumentView,
    SendCatalogDocumentToExchangeView,
    TrashCatalogDocumentView,
    RestoreCatalogDocumentView,
    PurgeCatalogDocumentView,
    BulkMoveCatalogDocumentsView,
    BulkTrashCatalogDocumentsView,
)

urlpatterns = [
    path('catalog/', CatalogFolderView.as_view(), name='catalog_root'),
    path('catalog/folder/<int:folder_id>/', CatalogFolderView.as_view(), name='catalog_folder'),
    path('catalog/trash/', CatalogTrashView.as_view(), name='catalog_trash'),
    path('catalog/folder/create/', CreateFolderView.as_view(), name='catalog_folder_create'),
    path('catalog/folder/<int:folder_id>/rename/', RenameCatalogFolderView.as_view(), name='catalog_folder_rename'),
    path('catalog/folder/<int:folder_id>/move/', MoveCatalogFolderView.as_view(), name='catalog_folder_move'),
    path('catalog/folder/<int:folder_id>/delete/', DeleteCatalogFolderView.as_view(), name='catalog_folder_delete'),
    path('catalog/upload/', UploadCatalogDocumentView.as_view(), name='catalog_upload'),
    path('catalog/download/<int:doc_id>/', DownloadCatalogDocumentView.as_view(), name='catalog_download'),
    path('catalog/rename/<int:doc_id>/', RenameCatalogDocumentView.as_view(), name='catalog_rename'),
    path('catalog/move/<int:doc_id>/', MoveCatalogDocumentView.as_view(), name='catalog_move'),
    path('catalog/send-to-exchange/<int:doc_id>/', SendCatalogDocumentToExchangeView.as_view(), name='catalog_send_to_exchange'),
    path('catalog/trash-doc/<int:doc_id>/', TrashCatalogDocumentView.as_view(), name='catalog_trash_doc'),
    path('catalog/restore/<int:doc_id>/', RestoreCatalogDocumentView.as_view(), name='catalog_restore'),
    path('catalog/purge/<int:doc_id>/', PurgeCatalogDocumentView.as_view(), name='catalog_purge'),
    path('catalog/bulk-move/', BulkMoveCatalogDocumentsView.as_view(), name='catalog_bulk_move'),
    path('catalog/bulk-trash/', BulkTrashCatalogDocumentsView.as_view(), name='catalog_bulk_trash'),
]
