from django.urls import path

from .views import (
    ExchangeFolderListView,
    ExchangeFolderView,
    ExchangeTrashView,
    CreateExchangeFolderView,
    RenameExchangeFolderView,
    MoveExchangeFolderView,
    DeleteExchangeFolderView,
    UploadExchangeFileView,
    DownloadExchangeFileView,
    RenameExchangeFileView,
    MoveExchangeFileView,
    SendExchangeFileToCatalogView,
    TrashExchangeFileView,
    RestoreExchangeFileView,
    PurgeExchangeFileView,
    BulkTrashExchangeFilesView,
    BulkDownloadExchangeFilesView,
    BulkMoveExchangeFilesView,
)

urlpatterns = [
    path('exchange/', ExchangeFolderListView.as_view(), name='exchange_inbox'),
    path('exchange/folder/<int:user_id>/', ExchangeFolderView.as_view(), name='exchange_folder'),
    path('exchange/folder/<int:user_id>/sub/<int:folder_id>/', ExchangeFolderView.as_view(), name='exchange_subfolder'),
    path('exchange/trash/', ExchangeTrashView.as_view(), name='exchange_trash'),
    path('exchange/folder/<int:user_id>/create/', CreateExchangeFolderView.as_view(), name='exchange_folder_create'),
    path('exchange/folder-rename/<int:folder_id>/', RenameExchangeFolderView.as_view(), name='exchange_folder_rename'),
    path('exchange/folder-move/<int:folder_id>/', MoveExchangeFolderView.as_view(), name='exchange_folder_move'),
    path('exchange/folder-delete/<int:folder_id>/', DeleteExchangeFolderView.as_view(), name='exchange_folder_delete'),
    path('exchange/upload/<int:user_id>/', UploadExchangeFileView.as_view(), name='exchange_upload'),
    path('exchange/download/<int:file_id>/', DownloadExchangeFileView.as_view(), name='exchange_download'),
    path('exchange/rename/<int:file_id>/', RenameExchangeFileView.as_view(), name='exchange_rename'),
    path('exchange/move/<int:file_id>/', MoveExchangeFileView.as_view(), name='exchange_move'),
    path('exchange/send-to-catalog/<int:file_id>/', SendExchangeFileToCatalogView.as_view(), name='exchange_send_to_catalog'),
    path('exchange/trash-file/<int:file_id>/', TrashExchangeFileView.as_view(), name='exchange_trash_file'),
    path('exchange/restore/<int:file_id>/', RestoreExchangeFileView.as_view(), name='exchange_restore'),
    path('exchange/purge/<int:file_id>/', PurgeExchangeFileView.as_view(), name='exchange_purge'),
    path('exchange/bulk-trash/', BulkTrashExchangeFilesView.as_view(), name='exchange_bulk_trash'),
    path('exchange/bulk-move/', BulkMoveExchangeFilesView.as_view(), name='exchange_bulk_move'),
    path('exchange/bulk-download/', BulkDownloadExchangeFilesView.as_view(), name='exchange_bulk_download'),
]
