from django.urls import path

from .views import (
    DepartmentFolderListView,
    DepartmentDocumentTrashView,
    CreateDepartmentFolderView,
    RenameDepartmentFolderView,
    MoveDepartmentFolderView,
    DeleteDepartmentFolderView,
    UpdateFolderAccessView,
    UploadDepartmentDocumentView,
    DownloadDepartmentDocumentView,
    RenameDepartmentDocumentView,
    MoveDepartmentDocumentView,
    SendDepartmentDocumentToExchangeView,
    TrashDepartmentDocumentView,
    RestoreDepartmentDocumentView,
    PurgeDepartmentDocumentView,
    BulkTrashDepartmentDocumentsView,
    DownloadDepartmentFolderView,
    UploadDepartmentArchiveView,
    BulkDownloadDepartmentDocumentsView,
    BulkMoveDepartmentDocumentsView,
)

urlpatterns = [
    path('deptdocs/', DepartmentFolderListView.as_view(), name='deptdocs_list'),
    path('deptdocs/folder/<int:folder_id>/', DepartmentFolderListView.as_view(), name='deptdocs_folder'),
    path('deptdocs/trash/', DepartmentDocumentTrashView.as_view(), name='deptdocs_trash'),
    path('deptdocs/folder/create/', CreateDepartmentFolderView.as_view(), name='deptdocs_folder_create'),
    path('deptdocs/folder/<int:folder_id>/rename/', RenameDepartmentFolderView.as_view(), name='deptdocs_folder_rename'),
    path('deptdocs/folder/<int:folder_id>/move/', MoveDepartmentFolderView.as_view(), name='deptdocs_folder_move'),
    path('deptdocs/folder/<int:folder_id>/delete/', DeleteDepartmentFolderView.as_view(), name='deptdocs_folder_delete'),
    path('deptdocs/folder/<int:folder_id>/access/', UpdateFolderAccessView.as_view(), name='deptdocs_folder_access'),
    path('deptdocs/upload/', UploadDepartmentDocumentView.as_view(), name='deptdocs_upload'),
    path('deptdocs/download/<int:doc_id>/', DownloadDepartmentDocumentView.as_view(), name='deptdocs_download'),
    path('deptdocs/rename/<int:doc_id>/', RenameDepartmentDocumentView.as_view(), name='deptdocs_rename'),
    path('deptdocs/move/<int:doc_id>/', MoveDepartmentDocumentView.as_view(), name='deptdocs_move'),
    path('deptdocs/send-to-exchange/<int:doc_id>/', SendDepartmentDocumentToExchangeView.as_view(), name='deptdocs_send_to_exchange'),
    path('deptdocs/trash-doc/<int:doc_id>/', TrashDepartmentDocumentView.as_view(), name='deptdocs_trash_doc'),
    path('deptdocs/restore/<int:doc_id>/', RestoreDepartmentDocumentView.as_view(), name='deptdocs_restore'),
    path('deptdocs/purge/<int:doc_id>/', PurgeDepartmentDocumentView.as_view(), name='deptdocs_purge'),
    path('deptdocs/bulk-trash/', BulkTrashDepartmentDocumentsView.as_view(), name='deptdocs_bulk_trash'),
    path('deptdocs/bulk-move/', BulkMoveDepartmentDocumentsView.as_view(), name='deptdocs_bulk_move'),
    path('deptdocs/bulk-download/', BulkDownloadDepartmentDocumentsView.as_view(), name='deptdocs_bulk_download'),
    path('deptdocs/upload-archive/', UploadDepartmentArchiveView.as_view(), name='deptdocs_upload_archive'),
    path('deptdocs/folder/<int:folder_id>/download-archive/', DownloadDepartmentFolderView.as_view(), name='deptdocs_folder_download'),
]
