# Generated by Django 4.2.5 on 2023-10-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ранг'),
        ),
    ]
