# Generated by Django 4.2.5 on 2023-10-30 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
