"""
Django settings for social_network project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""


from pathlib import Path
import os, sys
# import environ

# env = environ.Env()
# environ.Env.read_env(env_file=Path('./docker/env/.env.dev'))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = Path(__file__).parent.parent
sys.path.append(str(PROJECT_ROOT / 'apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = env('SECRET_KEY')
SECRET_KEY = 'django-insecure-=2#(c!ojl3^elc3w90tb^884+aw%ajo=zrb%wzl**(r8y51=@a'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = int(env('DEBUG', default=1))
DEBUG = True
# ALLOWED_HOSTS = env('ALLOWED_HOSTS').split()
ALLOWED_HOSTS = [
    'social.uk.ru',
    'www.social.uk.ru',
    'localhost',
    '127.0.0.1',
    # '192.168.1.100', # замените на IP вашего сервера
]


# CSRF_TRUSTED_ORIGINS = env('CSRF_TRUSTED_ORIGINS').split()
CSRF_TRUSTED_ORIGINS = [
    'http://social.uk.ru',
    'https://social.uk.ru',
]
X_FRAME_OPTIONS = 'SAMEORIGIN'

# Application definition

INSTALLED_APPS = [
    # 'daphne',  
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'compressor',
    'channels',
    'sitesettings.apps.SitesettingsConfig',
    'posts.apps.PostsConfig',
    'profiles.apps.ProfilesConfig',
    'comments.apps.CommentsConfig',
    'gallery.apps.GalleryConfig',
    'phonebook.apps.PhonebookConfig',
    'django_celery_beat',
    'netmap',
    'storage.apps.StorageConfig',
    'exchange.apps.ExchangeConfig',
    'catalog.apps.CatalogConfig',
    'deptdocs.apps.DeptdocsConfig',
    'django_private_chat2',
    'minio_storage',
]   

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'profiles.middleware.UserActivityMiddleware',
]
CORS_ORIGIN_ALLOW_ALL = True
ROOT_URLCONF = 'social_network.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'profiles.context_processors.birthday_notifications',
                'profiles.context_processors.notification_center',
                'profiles.context_processors.online_users',
                'profiles.context_processors.unread_messages_count',
                'sitesettings.context_processors.site_settings',
                'phonebook.context_processors.reference_books',
            ],
        },
    },
]

# WSGI_APPLICATION = 'social_network.wsgi.application'
ASGI_APPLICATION = 'social_network.routing.application'



CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}

# Celery — используется тот же Redis, что и для CHANNEL_LAYERS, но отдельная
# логическая база (db=1), чтобы не смешивать очередь задач с WS-трафиком.
# Расписание периодических задач (cleanup_orphan_files и т.д.) хранится в БД
# через django_celery_beat — настраивается через /admin/, а не через код,
# и работает одинаково на Windows (разработка) и Astra Linux (прод).
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/1'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/1'
CELERY_TIMEZONE = 'Europe/Moscow'  # держать в синхроне с TIME_ZONE ниже
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Под manage.py test задачи выполняются синхронно в том же процессе — без
# этого тесты массовых операций (bulk_move_documents, bulk_trash_documents)
# требовали бы поднятого Redis и запущенного celery worker просто чтобы
# проверить, что задача вообще что-то удаляет. .delay() при этом остаётся
# тем же вызовом в проверяемом коде — .apply()/eager подменяет только
# исполнение, тестировать приходится реальный путь, а не заглушку.
CELERY_TASK_ALWAYS_EAGER = 'test' in sys.argv
CELERY_TASK_EAGER_PROPAGATES = 'test' in sys.argv
# Без этого AsyncResult(task_id).state в eager-режиме не видит финальный
# SUCCESS — Celery по умолчанию не пишет результат eager-задачи в backend.
CELERY_TASK_STORE_EAGER_RESULT = 'test' in sys.argv

# Storage — единый сервис хранения файлов (apps/storage/ARCHITECTURE.md).
# Значения ниже — только умолчания: как только администратор откроет
# «Пределы файлового хранилища» в /admin/, действовать начинает запись в БД
# (storage/limits.py). Менять здесь имеет смысл лишь стартовые значения.
STORAGE_TRASH_RETENTION_DAYS = 30                # сколько дней запись лежит в корзине до автоудаления
STORAGE_MAX_UPLOAD_SIZE = 100 * 1024 * 1024      # 100 МБ на один файл
STORAGE_USER_QUOTA = 2 * 1024 * 1024 * 1024       # 2 ГБ на пользователя, None = без квоты
STORAGE_ORPHAN_RETENTION_DAYS = 7                # сколько blob лежит в ORPHAN до удаления

# Пределы массового скачивания одним zip. В отличие от одиночного файла,
# архив собирается на лету и потому идёт через воркер Daphne, а не через
# nginx (X-Accel-Redirect на несуществующий файл не сошлёшь): один запрос
# держит воркер на всё время выгрузки. Без предела «выделить всё и скачать»
# в общем каталоге было бы самообслуживаемым отказом портала.
STORAGE_ZIP_MAX_FILES = 200
STORAGE_ZIP_MAX_TOTAL_SIZE = 1024 * 1024 * 1024   # 1 ГБ в одном архиве

# Пределы обратной операции — загрузки архива с распаковкой на сайте
# (storage/archives.py). Сам файл архива ограничен STORAGE_MAX_UPLOAD_SIZE
# как обычная загрузка; здесь — что из него получится после распаковки.
STORAGE_ARCHIVE_MAX_FILES = 1000
STORAGE_ARCHIVE_MAX_TOTAL_SIZE = 2 * 1024 * 1024 * 1024   # 2 ГБ распакованного
# Отношение распакованного объёма к размеру архива, выше которого это
# считается zip-бомбой. Обычные офисные документы дают 2-5, сканы и
# картинки — около 1; 100 не достигается ничем осмысленным.
STORAGE_ARCHIVE_MAX_RATIO = 100

# Срок хранения по категориям, в днях. None = бессрочно.
# Пустой словарь означал бы, что cleanup_expired_objects не удаляет ничего
# никогда — включая вложения чата и обменника, которые должны истекать.
STORAGE_CATEGORY_TTL = {
    'chat': 7,
    'exchange': 7,
    'task': 90,
    'document': None,
    'catalog': None,
}

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
# DATABASES = {

#     'default': {

#         'ENGINE': 'django.db.backends.postgresql',

#         'NAME': env('POSTGRES_DB'),

#         'USER': env('POSTGRES_USER'),

#         'PASSWORD': env('POSTGRES_PASSWORD'),

#         'HOST': env('POSTGRES_HOST'),

#         'PORT': env('POSTGRES_PORT'),

#     }

# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'portal',
        'USER': 'postgres',
        'PASSWORD': '123',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}

# Другие параметры




# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True

AUTH_USER_MODEL = 'profiles.User'

# Куда отправлять неаутентифицированного посетителя. Без этой строки
# LoginRequiredMixin уводит на дефолтный /accounts/login/, которого в
# проекте нет, и защита превращается в 404 вместо формы входа.
LOGIN_URL = 'login'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'app/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_DIRS = []

# Адрес статики несёт время правки файла: без этого браузер кеширует
# скрипты «на глазок» и не спрашивает сервер часами — см.
# social_network/staticfiles.py.
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'social_network.staticfiles.VersionedStaticFilesStorage'},
}

# Обработка изображений (галерея, изображения постов). Не про storage:
# документы в нём обязаны доезжать байт в байт, оптимизируются только
# картинки на обычных ImageField (apps/storage/images.py).
IMAGE_MAX_SIDE = 1920        # до какой стороны уменьшать оригинал
IMAGE_QUALITY = 85           # качество JPEG при пересжатии
IMAGE_THUMBNAIL_SIDE = 480   # сторона миниатюры для сетки и ленты

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Под manage.py test медиа уходит во временный каталог, а не в боевой
# media/.
#
# Django создаёт и удаляет тестовую БД, но файловую систему за собой не
# убирает. Тесты storage реально пишут blob'ы на диск, поэтому каждый
# прогон оставлял их в media/storage/blobs/ навсегда: записи FileBlob
# исчезали вместе с тестовой БД, а файлы — нет. За несколько дней работы
# так накопилось 2862 файла при 25 записях в БД.
#
# Вдобавок это ломало саму дедупликацию в тестах: имя файла равно
# checksum, и на втором прогоне FileSystemStorage находил файл уже
# существующим и дописывал случайный суффикс (<checksum>_B24AkEu) — то
# есть на диске лежали сотни копий одного содержимого, ровно то, ради
# предотвращения чего storage и писался.
#
# Каталог не удаляется автоматически: он в системном temp, ОС вычистит
# его сама, а сохранённые файлы иногда нужны для разбора упавшего теста.
if 'test' in sys.argv:
    import tempfile

    MEDIA_ROOT = tempfile.mkdtemp(prefix='portal-test-media-')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

COMPRESS_ROOT = BASE_DIR / 'static'

COMPRESS_ENABLED = True

STATICFILES_FINDERS = ('compressor.finders.CompressorFinder',)

# Параметры хранилища файлов
# DEFAULT_FILE_STORAGE = env('DEFAULT_FILE_STORAGE')
# AWS_STORAGE_BUCKET_NAME = env('AWS_STORAGE_BUCKET_NAME')
# AWS_ACCESS_KEY_ID = env('AWS_ACCESS_KEY_ID')
# AWS_SECRET_ACCESS_KEY = env('AWS_SECRET_ACCESS_KEY')
# AWS_S3_ENDPOINT_URL = env('AWS_S3_ENDPOINT_URL')
# DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
# AWS_STORAGE_BUCKET_NAME = 'storage'
# AWS_ACCESS_KEY_ID = 'admin'
# AWS_SECRET_ACCESS_KEY = 'password'
# AWS_S3_ENDPOINT_URL = 'http://localhost:9000/'

# DEFAULT_FILE_STORAGE = env('DEFAULT_FILE_STORAGE')
# MINIO_STORAGE_ENDPOINT = env('MINIO_STORAGE_ENDPOINT')
# MINIO_STORAGE_ACCESS_KEY = env('MINIO_STORAGE_ACCESS_KEY')
# MINIO_STORAGE_SECRET_KEY = env('MINIO_STORAGE_SECRET_KEY')
# MINIO_STORAGE_USE_HTTPS = env('MINIO_STORAGE_USE_HTTPS')
# # MINIO_STORAGE_MEDIA_OBJECT_METADATA = env('MINIO_STORAGE_MEDIA_OBJECT_METADATA')
# MINIO_STORAGE_MEDIA_BUCKET_NAME = env('MINIO_STORAGE_MEDIA_BUCKET_NAME')
# MINIO_STORAGE_AUTO_CREATE_MEDIA_BUCKET = env('MINIO_STORAGE_AUTO_CREATE_MEDIA_BUCKET')
