# Generated by Django 5.0.1 on 2026-07-24 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_private_chat2', '0002_auto_20210329_2217'),
        ('profiles', '0002_remove_user_online_user_last_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=8, verbose_name='Эмодзи')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='django_private_chat2.messagemodel', verbose_name='Сообщение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Реакция на сообщение',
                'verbose_name_plural': 'Реакции на сообщения',
                'unique_together': {('message', 'user')},
            },
        ),
    ]
