# Generated by Django 5.0.1 on 2026-07-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_messagereaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagereaction',
            options={'ordering': ('emoji',), 'verbose_name': 'Реакция на сообщение', 'verbose_name_plural': 'Реакции на сообщения'},
        ),
        migrations.AddField(
            model_name='user',
            name='security_answer',
            field=models.CharField(blank=True, max_length=255, verbose_name='Проверочное слово для сброса пароля'),
        ),
    ]
