# Generated by Django 5.0.1 on 2026-07-27 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_messagereaction_options_user_security_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='cover/', verbose_name='Обложка профиля'),
        ),
        migrations.AddField(
            model_name='user',
            name='employee_status',
            field=models.CharField(choices=[('at_work', 'На месте'), ('sick_leave', 'Больничный'), ('business_trip', 'Командировка'), ('do_not_disturb', 'Не беспокоить')], default='at_work', max_length=20, verbose_name='Статус сотрудника'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('event_type', models.CharField(choices=[('personal', 'Личное'), ('corporate', 'Корпоративное')], default='personal', max_length=20, verbose_name='Тип события')),
                ('date', models.DateField(verbose_name='Дата')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Событие календаря',
                'verbose_name_plural': 'События календаря',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='Текст заметки')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='note', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Личная заметка',
                'verbose_name_plural': 'Личные заметки',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Задача')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Срок выполнения')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['is_completed', 'due_date', '-created'],
            },
        ),
    ]
