# Generated by Django 5.0.1 on 2026-07-28 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_user_cover_user_employee_status_event_note_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='source_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_event', to='profiles.task', verbose_name='Связанная задача'),
        ),
    ]
