# Generated by Django 5.0.1 on 2026-07-28 13:08

from django.db import migrations, models


def backfill_status(apps, schema_editor):
    Task = apps.get_model('profiles', 'Task')
    Task.objects.filter(is_completed=True).update(status='done')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_task_assigned_by_alter_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_edited',
            field=models.BooleanField(default=False, verbose_name='Изменена постановщиком после создания'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('not_started', 'Не начата'), ('in_progress', 'В работе'), ('done', 'Выполнена')], default='not_started', max_length=20, verbose_name='Статус'),
        ),
        migrations.RunPython(backfill_status, noop),
    ]
