# Generated by Django 5.0.1 on 2026-07-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_task_is_edited_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recurrence',
            field=models.CharField(choices=[('none', 'Не повторять'), ('weekly', 'Каждую неделю'), ('monthly', 'Каждый месяц'), ('yearly', 'Каждый год')], default='none', max_length=10, verbose_name='Повтор'),
        ),
    ]
