# Generated by Django 5.0.1 on 2026-07-29 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_event_recurrence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['position', '-updated'], 'verbose_name': 'Личная заметка', 'verbose_name_plural': 'Личные заметки'},
        ),
        migrations.AddField(
            model_name='note',
            name='color',
            field=models.CharField(choices=[('yellow', 'Жёлтый'), ('pink', 'Розовый'), ('blue', 'Голубой'), ('green', 'Зелёный'), ('purple', 'Фиолетовый')], default='yellow', max_length=10, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='note',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
