# Generated by Django 5.0.1 on 2026-07-29 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_private_chat2', '0002_auto_20210329_2217'),
        ('profiles', '0013_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reply_info', to='django_private_chat2.messagemodel', verbose_name='Сообщение-ответ')),
                ('reply_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='django_private_chat2.messagemodel', verbose_name='Исходное сообщение')),
            ],
        ),
    ]
