# Generated by Django 5.0.1 on 2026-07-30 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_photo_postfile_postimage'),
        ('profiles', '0014_messagereply'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='posts.post', verbose_name='Пост'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('task_assigned', 'Поставлена задача'), ('task_edited', 'Задача изменена'), ('task_status_changed', 'Статус задачи изменён'), ('post_commented', 'Новый комментарий к посту')], max_length=30, verbose_name='Тип'),
        ),
    ]
