# Generated by Django 5.0.1 on 2026-08-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_notification_post_alter_notification_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('task_assigned', 'Поставлена задача'), ('task_edited', 'Задача изменена'), ('task_status_changed', 'Статус задачи изменён'), ('post_commented', 'Новый комментарий к посту'), ('file_shared', 'Новый файл')], max_length=30, verbose_name='Тип'),
        ),
    ]
