# Generated by Django 5.0.1 on 2026-08-10 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_rename_position_rank_to_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Вид номера')),
                ('mask', models.CharField(blank=True, help_text='Например: 8 (999) 999-99-99. Пусто — вводить как есть.', max_length=50, verbose_name='Маска ввода')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок в списке')),
            ],
            options={
                'verbose_name': 'Вид телефонного номера',
                'verbose_name_plural': 'Виды телефонных номеров',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Звание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок в списке')),
            ],
            options={
                'verbose_name': 'Звание',
                'verbose_name_plural': 'Звания',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Должность')),
                ('max_holders', models.PositiveIntegerField(default=0, verbose_name='Сколько человек может занимать (0 — без ограничения)')),
                ('assignable_by_user', models.BooleanField(default=False, help_text='Оставьте выключенным для руководящих должностей — их назначает только администратор.', verbose_name='Сотрудник может выбрать эту должность сам')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок в списке')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='profiles.category', verbose_name='Подразделение')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='profiles.position', verbose_name='Подчиняется должности')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности (структура организации)',
                'ordering': ['order', 'name'],
                'unique_together': {('name', 'department')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holders', to='profiles.position', verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holders', to='profiles.rank', verbose_name='Звание'),
        ),
        migrations.CreateModel(
            name='UserPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, verbose_name='Номер')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='numbers', to='profiles.phonetype', verbose_name='Вид номера')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Телефон сотрудника',
                'verbose_name_plural': 'Телефоны сотрудников',
                'ordering': ['type__order', 'type__name'],
                'unique_together': {('user', 'type')},
            },
        ),
    ]
