# Generated by Django 5.0.1 on 2026-08-10 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_orgstructure_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_9',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_hc',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_pts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_zs',
        ),
        migrations.RemoveField(
            model_name='user',
            name='position_text',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rank_text',
        ),
    ]
