# Generated by Django 5.0.1 on 2026-08-21 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_private_chat2', '0002_auto_20210329_2217'),
        ('profiles', '0020_orgstructure_cleanup'),
        ('storage', '0004_storagelimits'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='Размер')),
                ('is_image', models.BooleanField(default=False, verbose_name='Показывать картинкой')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда удалён по сроку')),
                ('file_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='storage.fileobject', verbose_name='Файл')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='django_private_chat2.messagemodel', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Вложение сообщения',
                'verbose_name_plural': 'Вложения сообщений',
                'ordering': ('id',),
            },
        ),
    ]
