# Generated by Django 5.0.1 on 2026-08-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_postfile_file_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='photos/%Y/%m/%d/thumbs/', verbose_name='Миниатюра'),
        ),
    ]
