# Generated by Django 5.0.1 on 2026-08-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_poll_polloption_pollvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='show_voters',
            field=models.BooleanField(default=False, verbose_name='Показывать, кто какой вариант выбрал'),
        ),
    ]
