# Generated by Django 5.0.1 on 2026-07-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Название организации', max_length=100, verbose_name='Название организации')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sitesettings/', verbose_name='Логотип')),
                ('footer_text', models.CharField(blank=True, max_length=255, verbose_name='Текст в футере')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
