# Generated by Django 4.2.5 on 2023-11-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_rename_posts_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_pubdate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
    ]
