# Generated by Django 5.0.1 on 2026-08-03 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangefile',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Файл обменника', 'verbose_name_plural': 'Файлы обменника'},
        ),
        migrations.AlterField(
            model_name='exchangefile',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_files', to=settings.AUTH_USER_MODEL, verbose_name='Владелец папки'),
        ),
        migrations.AlterField(
            model_name='exchangefile',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто загрузил'),
        ),
    ]
