# Generated by Django 5.0.1 on 2026-08-19 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidr', models.CharField(help_text='Например, 10.10.0.0/24', max_length=18, unique=True, verbose_name='Подсеть')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('is_scan_enabled', models.BooleanField(default=True, verbose_name='Обходить')),
                ('probe_ports', models.BooleanField(default=True, verbose_name='Проверять порты')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Подсеть',
                'verbose_name_plural': 'Подсети',
                'ordering': ['cidr'],
            },
        ),
        migrations.CreateModel(
            name='ScanRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('scanned', models.PositiveIntegerField(default=0, verbose_name='Опрошено адресов')),
                ('responded', models.PositiveIntegerField(default=0, verbose_name='Ответили')),
                ('created', models.PositiveIntegerField(default=0, verbose_name='Новых записей')),
                ('error', models.TextField(blank=True)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('subnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='netmap.subnet')),
            ],
            options={
                'verbose_name': 'Обход сети',
                'verbose_name_plural': 'Обходы сети',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='NetworkAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(protocol='IPv4', unique=True, verbose_name='IP-адрес')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название устройства')),
                ('kind', models.CharField(blank=True, choices=[('workstation', 'Рабочее место'), ('server', 'Сервер'), ('printer', 'Принтер или МФУ'), ('network', 'Сетевое оборудование'), ('phone', 'IP-телефон'), ('camera', 'Камера'), ('other', 'Прочее')], max_length=20, verbose_name='Тип')),
                ('room', models.CharField(blank=True, max_length=50, verbose_name='Кабинет')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('is_excluded', models.BooleanField(default=False, verbose_name='Не опрашивать')),
                ('hostname', models.CharField(blank=True, max_length=255, verbose_name='Имя в DNS')),
                ('mac', models.CharField(blank=True, max_length=17, verbose_name='MAC')),
                ('os_guess', models.CharField(blank=True, choices=[('windows', 'Windows'), ('linux', 'Linux / Астра'), ('device', 'Сетевое устройство'), ('', 'Не определена')], max_length=20)),
                ('open_ports', models.JSONField(blank=True, default=list)),
                ('ttl', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reply_method', models.CharField(blank=True, max_length=20, verbose_name='Ответил через')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний ответ')),
                ('last_scan_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний опрос')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('subnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='netmap.subnet')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
                'ordering': ['ip'],
            },
        ),
    ]
