# Generated by Django 5.0.1 on 2026-07-31 08:17

import django.db.models.deletion
import storage.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileBlob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=storage.models.blob_upload_path)),
                ('checksum', models.CharField(max_length=64, unique=True)),
                ('size', models.PositiveBigIntegerField()),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Активен'), ('orphan', 'Без ссылок (ожидает удаления)')], db_index=True, default='active', max_length=10)),
                ('orphaned_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'orphaned_at'], name='storage_fil_status_65e6a2_idx')],
            },
        ),
        migrations.CreateModel(
            name='FileObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('chat', 'Вложение чата'), ('exchange', 'Обменник'), ('document', 'Документ подразделения'), ('catalog', 'Информационный каталог'), ('task', 'Файл задачи')], db_index=True, max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('blob', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_objects', to='storage.fileblob')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StorageAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('upload', 'Загрузка'), ('detach', 'Отвязка ссылки'), ('purge', 'Физическое удаление'), ('restore', 'Восстановление из ORPHAN')], max_length=20)),
                ('checksum', models.CharField(db_index=True, max_length=64)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('consumer', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
