# Generated by Django 5.0.1 on 2026-08-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_replace_expired_objects_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageLimits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_upload_size_mb', models.PositiveIntegerField(default=100, help_text='Действует на любую загрузку: файл, вложение поста, файл внутри архива.', verbose_name='Максимальный размер одного файла, МБ')),
                ('user_quota_mb', models.PositiveIntegerField(blank=True, default=2048, help_text='Пусто — без квоты. Считается по уникальным файлам: копия чужого файла места не занимает.', null=True, verbose_name='Квота на сотрудника, МБ')),
                ('trash_retention_days', models.PositiveIntegerField(default=30, verbose_name='Сколько дней хранить в корзине')),
                ('orphan_retention_days', models.PositiveIntegerField(default=7, help_text='После этого срока содержимое удаляется с диска окончательно.', verbose_name='Сколько дней хранить файл без ссылок')),
                ('zip_max_files', models.PositiveIntegerField(default=200, verbose_name='Массовое скачивание: файлов в архиве')),
                ('zip_max_total_size_mb', models.PositiveIntegerField(default=1024, verbose_name='Массовое скачивание: общий объём, МБ')),
                ('archive_max_files', models.PositiveIntegerField(default=1000, verbose_name='Загрузка архива: файлов внутри')),
                ('archive_max_total_size_mb', models.PositiveIntegerField(default=2048, verbose_name='Загрузка архива: объём после распаковки, МБ')),
                ('archive_max_ratio', models.PositiveIntegerField(default=100, help_text='Во сколько раз распакованное может быть больше архива. Выше — считается zip-бомбой.', verbose_name='Загрузка архива: предел сжатия')),
                ('chat_ttl_days', models.PositiveIntegerField(blank=True, default=7, help_text='Пусто — хранить бессрочно.', null=True, verbose_name='Вложения чата: срок хранения, дней')),
                ('exchange_ttl_days', models.PositiveIntegerField(blank=True, default=7, help_text='Пусто — хранить бессрочно.', null=True, verbose_name='Обменник: срок хранения, дней')),
            ],
            options={
                'verbose_name': 'Пределы файлового хранилища',
                'verbose_name_plural': 'Пределы файлового хранилища',
            },
        ),
    ]
