# Generated by Django 5.0.1 on 2026-08-03 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deptdocs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentdocument',
            name='allowed_departments',
        ),
        migrations.CreateModel(
            name='DepartmentFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allowed_users', models.ManyToManyField(related_name='accessible_department_folders', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='deptdocs.departmentfolder')),
            ],
            options={
                'verbose_name': 'Папка документов отдела',
                'verbose_name_plural': 'Папки документов отдела',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='departmentdocument',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='deptdocs.departmentfolder'),
        ),
    ]
