# Generated by Django 5.0.1 on 2024-03-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phonebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.FileField(blank=True, null=True, upload_to='Phonebook/', verbose_name='Справочники')),
            ],
        ),
    ]
