# Generated by Django 5.0.1 on 2024-03-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonebook',
            name='title',
            field=models.CharField(default=2, max_length=255, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
