# Generated by Django 5.0.1 on 2026-07-31 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0002_phonebook_file_object'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonebook',
            options={'verbose_name': 'Справочники', 'verbose_name_plural': 'Справочники'},
        ),
    ]
