# Generated by Django 5.0.1 on 2026-08-21 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0005_clear_backfilled_created_at'),
        ('storage', '0004_storagelimits'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonebook',
            name='conversion_error',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='phonebook',
            name='conversion_status',
            field=models.CharField(blank=True, choices=[('', 'Не требуется'), ('pending', 'Готовится'), ('done', 'Готово'), ('failed', 'Не удалось')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='phonebook',
            name='pdf_file_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='storage.fileobject', verbose_name='Версия для просмотра (PDF)'),
        ),
    ]
