# Generated by Django 5.0.1 on 2026-08-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='gallery/thumbs/', verbose_name='Миниатюра'),
        ),
    ]
